name: kchat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  get_it: ^8.0.3
  dash_chat_2: ^0.0.21
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  firebase_database: ^11.3.6
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  firebase_analytics: ^11.4.6
  delightful_toast: ^1.1.0
  path: ^1.9.1
  image_picker: ^1.1.2
  badges: ^3.1.2
  push: ^3.3.3
  firebase_messaging: ^15.2.6
  get: ^4.7.2
  http: ^1.4.0
  pdf: ^3.11.3
  syncfusion_flutter_pdf: ^29.2.7
  syncfusion_flutter_pdfviewer: ^29.2.7
  file_picker: ^10.1.9
  chat_gpt_flutter: ^1.0.16
  chat_gpt_sdk: ^3.1.5
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12
  toastification: ^3.0.2
  supabase_flutter: ^2.9.0
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.5
  flutter_markdown: ^0.7.7+1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  assets:
    - .env

  uses-material-design: true
